### PR TITLE
Adding semicolons (;) to insert statements

### PR DESCRIPTION
**Pull request by HillmerCh**
To fix and import sql issue

### CODE REVIEW

**Comment by cescoffier** [comment]
Is there any reason for this addition? If it can be omitted, why should we add them?

**Comment by rsvoboda** [comment]
hibernate-orm-guide says

```
[NOTE]
====
Quarkus supports `.sql` file with SQL statements or comments spread over multiple lines.
Each SQL statement must be terminated by a semicolon.
====
```

**Comment by HillmerCh** [comment]
I got this exception both H2 and PSQL databases: 

"Caused by: org.hibernate.tool.hbm2ddl.ImportScriptException: Error during import script parsing."


javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:113)
at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:67)
at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:54)
at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:109)
at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:57)
at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:77)
at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits18.deploy_0(HibernateOrmProcessor$startPersistenceUnits18.zig:51)
at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits18.deploy(HibernateOrmProcessor$startPersistenceUnits18.zig:70)
at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:90)
at io.quarkus.runtime.Application.start(Application.java:84)
at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:127)
at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:180)
at io.quarkus.dev.DevModeMain.start(DevModeMain.java:94)
at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: org.hibernate.tool.hbm2ddl.ImportScriptException: Error during import script parsing.

**Comment by gsmet** [comment]
@cescoffier it can't be omitted. We changed the parser to support multiline statements.

**Comment by gsmet** [comment]
@HillmerCh hmm, what's the difference with the one I already merged: https://github.com/quarkusio/todo-demo-app/pull/3/files ?

**Comment by HillmerCh** [comment]
@gsmet there is another branch named postgresql, that branch has the same file without semicolons, this PR is for the quarkusio:postgresql branch

**Comment by gsmet** [comment]
Ah, OK, thanks!

**Comment by gsmet** [comment]
Merged, too. Thanks a lot for taking the time to push PRs!

**Pull request merged**
