### PR TITLE
Use metrics annotations

### PR DESCRIPTION
**Pull request by jarryDk**
Upgrade to quarkus 1.12.1.Final
Add metrics annotations to TodoResource#create
Add MicroProfile Metrics section to README.md
Add start Postgres with podman to README.md

### CODE REVIEW

**Comment by cescoffier** [comment]
@ebullient should'nt we use Micrometer instead?

**Comment by jarryDk** [comment]
@cescoffier : @kenfinnigan will agree with you https://quarkus.io/blog/micrometer-metrics/, but to keep the sample code simple I have chosen microprofile-metrics.

On a daily basis I work with Wildfly / EAP where we have microprofile-metrics out of the box.

**Comment by kenfinnigan** [comment]
We should definitely not be using MP Metrics anymore, and also not using annotations.

Especially in this case where I'm pretty sure the metrics being defined on a JAX-RS endpoint will be already producing metrics equivalent to the annotations with Micrometer

**Comment by jarryDk** [comment]
Tried to remove
````
<dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-metrics</artifactId>
 </dependency>
````
before introducing

````
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-micrometer-registry-prometheus</artifactId>
</dependency>
````


Now we have the next issue - quarkus-smallrye-graphql depends on quarkus-smallrye-metrics

````
2021-03-05 07:19:07,648 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:445)
	... 15 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/microprofile/metrics/Tag
	at io.smallrye.graphql.cdi.metrics.MetricsService.getTags(MetricsService.java:84)
	at io.smallrye.graphql.cdi.metrics.MetricsService.createOperation(MetricsService.java:37)
	at io.smallrye.graphql.execution.event.EventEmitter.fireCreateOperation(EventEmitter.java:142)
	at io.smallrye.graphql.bootstrap.Bootstrap.addRootObject(Bootstrap.java:180)
	at io.smallrye.graphql.bootstrap.Bootstrap.addQueries(Bootstrap.java:148)
	at io.smallrye.graphql.bootstrap.Bootstrap.generateGraphQLSchema(Bootstrap.java:122)
	at io.smallrye.graphql.bootstrap.Bootstrap.bootstrap(Bootstrap.java:98)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:44)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:40)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer_ClientProxy.initialize(GraphQLProducer_ClientProxy.zig:160)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLRecorder.createExecutionService(SmallRyeGraphQLRecorder.java:29)
	at io.quarkus.deployment.steps.SmallRyeGraphQLProcessor$buildExecutionService-167583418.deploy_1(SmallRyeGraphQLProcessor$buildExecutionService-167583418.zig:3045)
	at io.quarkus.deployment.steps.SmallRyeGraphQLProcessor$buildExecutionService-167583418.deploy(SmallRyeGraphQLProcessor$buildExecutionService-167583418.zig:45)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:414)
	... 15 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.microprofile.metrics.Tag
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:428)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:378)
	... 29 more
````

**Comment by jmartisk** [comment]
If there is SmallRye GraphQL involved, you need to add a dependency on the MP Metrics API (`org.eclipse.microprofile.metrics:microprofile-microprofile-metrics-api`) because SmallRye GraphQL uses it. I think you'll also need `quarkus.micrometer.binder.mp-metrics.enabled=true` to tell the Micrometer extension to handle it.

**Comment by rsvoboda** [comment]
`because SmallRye GraphQL uses it.` ... Shouldn't SmallRye GraphQL pull the MP metrics API dependency?
https://github.com/smallrye/smallrye-graphql/blob/master/pom.xml#L104 has it defined.

**Comment by jmartisk** [comment]
The module which actually depends on it declares it as provided: https://github.com/smallrye/smallrye-graphql/blob/master/server/implementation-cdi/pom.xml#L26 - it's optional on purpose, we don't want to drag it in if the application is not using metrics.

**Comment by gsmet** [comment]
@jmartisk hmm but you end up with a project that does not compile if you're using Micrometer? That sounds a bit weird.

**Comment by jmartisk** [comment]
Well, yes, but it's a temporary thing until we decouple SR-GraphQL from MP Metrics, which should be soon.

**Comment by ebullient** [comment]
you don’t need the binder option.. if MP Metrics API is present, the Micrometer extension will provide the adapter. We perhaps should have had the graphql extension include the mp metrics api, as apps can’t compile without it.

**Comment by jmartisk** [comment]
> We perhaps should have had the graphql extension include the mp metrics api, as apps can’t compile without it.

They can, if GraphQL metrics are turned off.

**Pull request closed without merging**
