### PR TITLE
Updated to 1.6 and some more

### PR DESCRIPTION
**Pull request by phillip-kruger**
Hi. I am not sure if you still maintain this example application. I updated for myself for a talk, so thought I'll share if you are interested. Else just close the PR :)

What I have done:

- Upgrade to v1.6
- Add OpenAPI and Swagger UI to the REST Endpoints
- Add MicroProfile Health
- Add MicroProfile Metrics
- Add MicroProfile GraphQL
- Added links (of above) for convenience (in the GUI)
- Added tests 

I am happy to maintain this app if this is something we want.

### CODE REVIEW

**Comment by gsmet** [comment]
@cescoffier what's your take on this, it's your app?

If we plan to maintain it, we should:
* set up GH actions
* get rid of using separate branches for each supported database and use a profile

**Comment by cescoffier** [comment]
This repo is used by the openshift team if I'm not mistaken. So we should give it some love and implement the automation. I'm not sure about the automation as it can complexify a bit the deployment (you would need to pass the profile to openshift which leads to configuring the s2i). I would need the input from openshift.

**Comment by cescoffier** [comment]
@sshaaf what's your take on this?

**Comment by sshaaf** [comment]
We have been using this demo in the runtimes team as well for customers and events. 

Using Openshift to delpoy: I would suggest we should keep the deployment open, for folks who might want to deploy it elsewhere. If needed we could just provide some docs on how to deploy to openshift. But demo on a local machine should just be good enough IMHO.

I also ended up working on my own fork and updating it there; it might help to maintain this since it helps all of us forks.

**Comment by phillip-kruger** [comment]
Hi @sshaaf, @gsmet, @cescoffier  - so we can merge this here, and then let's use the issues to add all the other things we want to do, like:

- set up GH actions
- get rid of using separate branches for each supported database and use a profile
- Document how to demo this on OpenShift (local and remote) 

etc.

w.d.y.t ?

**Comment by cescoffier** [comment]
I had a quick chat with Shaaf.
We should experiment with profiles an see how far we can go and document
the OpenShift deployment in the readme.

So, we can merge this PR and play with profiles to see how it goes.

Le jeu. 16 juil. 2020 à 19:17, Phillip Krüger <notifications@github.com> a
écrit :

**Comment by phillip-kruger** [comment]
Cool. I can not merge. So sure who can. I'll create issues for the items as discussed. Thanks :)

**Comment by cescoffier** [comment]
Merged!

**Comment by phillip-kruger** [comment]
Thanks :)

**Pull request merged**
